name: Imagina build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.AZURE_CONTAINER_USERNAME }}
        password: ${{ secrets.AZURE_CONTAINER_PWD}}
        login-server: imaginaproject.azurecr.io
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag imagina-project-grupo2:$(date +%s)
      
    - name: Push the Docker image
      run: docker push --tag imagina-project-grupo2:$(date +%s)
